---
name: Beta
OSC:
  port: 57130
populationSize: 24
keepFittest: 8
mutationProb: 0.05
genes:
    "energy":
        min: 0
        max: 255
        current: 128
        round: false
        activates: OnBar
    "vibe":
        min: 1
        max: 12
        current: 6
        round: false
        activates: OnBar
    "theme":
        min: 1
        max: 12
        current: 6
        round: false
        activates: OnBar

# Configure interfaces
# OSC -> SuperCollider
SuperCollider:
    addr: 127.0.0.1
    port: 57120
# Input type
input:
    type: midi
    name: "Oxygen 25"
    map:
        "energy":
            down: 24
            up: 26
        "vibe":
            down: 28
            up: 29
        "theme":
            down: 31
            up: 33

